<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="XPacmanEvent" nsURI="http://org.tetrabox.example.pacman.xpacman/scenario/XPacmanEvent/" nsPrefix="XPacmanEvent">
  <eClassifiers xsi:type="ecore:EClass" name="XPacmanDSLEvent" abstract="true">
    <eSuperTypes href="http://www.gemoc.org/scenario#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PacmanEvent" abstract="true" eSuperTypes="//XPacmanDSLEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pacman" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="../../org.tetrabox.example.pacman.xpacman/model/XPacman.ecore#//Pacman"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PacmanDownEvent" eSuperTypes="//PacmanEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="PacmanLeftEvent" eSuperTypes="//PacmanEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="PacmanRightEvent" eSuperTypes="//PacmanEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="PacmanUpEvent" eSuperTypes="//PacmanEvent"/>
</ecore:EPackage>
